### ISSUE TITLE
Issues with multiple excludes and regexp

### ISSUE THREAD

**Issue by andreassolberg** [custom-cards/flex-table-card#1]
This does not work:

```
          exclude:
            - light\.fibaro.*
            - light.group_2
```

When I comment out the second line, it works:
```
          exclude:
            - light\.fibaro.*
            # - light.group_2
```

From the docs, multiple excludes should be allowed in a list, right? And the format is regexp.

**Comment by daringer** [comment]
hmmm, feels like a bug, let me check that

**Comment by daringer** [comment]
more than just a bug, simply messy code; fixed and re-worked regex stuff. Would be great if you could check, if it works for you as expected.

generally you can omit any `*` in the excludes, as _any_ match will exclude the entity from the entity list.

**Comment by daringer** [comment]
@andreassolberg is this ok for you as this works right now, would close this issue then...

**Comment by daringer** [comment]
hope the issue is resolved for you, feel free to re-open it if it's not the case
closing...
