### ISSUE TITLE
column width

### ISSUE THREAD

**Issue by UniCizin** [custom-cards/flex-table-card#114]
hey guys,

i need your help with formatting the size of a column.

my current config

type: custom:flex-table-card
title: Bundesliga Tabelle
entities:
  include: sensor.bund_scoreboard2
  exclude: zwave.unknown_node*
columns:
  - name: Platz
    data: entries
    modify: x.stats[10].value
  - name: Logo
    data: entries
    modify: ''' <img src="'' + x.team.logos[0].href + ''"style="width: 20%">'''
    align: left
  - name: Mannschaft
    data: entries
    modify: x.team.name
  - name: Spiele
    data: entries
    modify: x.stats[0].value
  - name: Punkte
    data: entries
    modify: x.stats[3].value

if you now look at the screenshot, you see that the logo column is to big. 
How can i get it smaller? 
![flex_card_screenie](https://github.com/custom-cards/flex-table-card/assets/41308043/fcc47f2b-4f71-47da-b30b-57b3b40c751b)

**Comment by ildar170975** [comment]
Try this:
```
          css:
            tbody tr td:nth-child(2)+: 'width: 32px;'
```

**Comment by UniCizin** [comment]
that worked. 
thank you very much :)
