### ISSUE TITLE
Error "Cannot set properties of null (setting 'onclick')"

### ISSUE THREAD

**Issue by edersong** [custom-cards/flex-table-card#115]
After the upgrade to v0.7.4, one of my cards are reporting the error `Cannot set properties of null (setting 'onclick')` even there is no `onclick` on his code.

![image](https://github.com/custom-cards/flex-table-card/assets/64137913/f2db1710-61ba-4afb-8310-e3eef07a2954)

**Comment by MaximeNagel** [comment]
I have the same problem if I use name: '' in my card, maybe it's the reason for this.

Example: 

columns:
        - data: entity_picture
          align: center
          name: ''
          icon: mdi:gas-station
          modify: '''<img src="'' + x + ''"style="height: 35px;width:100%">'''

**Comment by JeffCrum1** [comment]
I had HTML TITLE tags on my names to give info on a mouse over.

Once I removed those, the error went away.

**Comment by EdLeckert** [comment]
The fix for this is in my repo. If you need it sooner or want to help me test it and are in a position to update `flex-table-card.js` manually, it is here:

`https://github.com/EdLeckert/flex-table-card/tree/fix-generate-new-id-for-onclick-error`

**Comment by MaximeNagel** [comment]
> The fix for this is in my repo. If you need it sooner or want to help me test it and are in a position to update `flex-table-card.js` manually, it is here:
> 
> `https://github.com/EdLeckert/flex-table-card/tree/fix-generate-new-id-for-onclick-error`

It works for me ! Thx for this quick hotfix 😃

**Comment by JeffCrum1** [comment]
Did not work in my situation.

Here is the column code that is at issue:
```
        - name: >-
            <div title="Clinch Indicator:&#10; * : Clinched Best League
            Record&#10; z : Clinched Playoff Birth&#10; x : Clinched
            Division&#10; - : In The Hunt&#10; e : Eliminated">C</div>
          data: entries
          modify: >-
            if(typeof x.stats.find(y=>y.abbreviation == 'CLINCH') !==
            'undefined' ){x.stats.find(y=>y.abbreviation ==
            'CLINCH').displayValue}else{'-'}
```

If I remove the HTML, it works fine.

Let me know if you need more code for the whole card.

Thanks

**Comment by EdLeckert** [comment]
@JeffCrum1: What behavior or error are you seeing? 

I'm getting the character "C" with the key for "Clinch Indicator" on hover. I don't have the data to make the `modify` work, but the `name` works fine for me.

**Comment by JeffCrum1** [comment]
Understood Ed.  Thanks.  I will get you more info later tonight.

I can probably even mock up something to make it work/not work.

**Comment by JeffCrum1** [comment]
So sorry.  I didn't realize I needed to delete the .gz file when manually updating.

All good now!

**Comment by daringer** [comment]
there also is a 0.7.5 release now with all the fixes included...
