### ISSUE TITLE
Downloaded 0.7.4 - still shows ver 0.7.3

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/flex-table-card#118]
In source code:
![изображение](https://github.com/custom-cards/flex-table-card/assets/71872483/dc369bf1-1f0f-4698-984a-334ce20de381)

**Comment by daringer** [comment]
thanks, fixed with: https://github.com/custom-cards/flex-table-card/commit/447cc0c4842a8d88f42edd5ad61ec47dc9c41552
