### ISSUE TITLE
Feature Request: Style based on cell contents

### ISSUE THREAD

**Issue by dvanderb** [custom-cards/flex-table-card#13]
It would be great to be able to apply styles(think card-mod or card-modder) to cells based on their contents.  For example I have a table showing device status for wireless sensors and I'd like to be able to color the cell text red if the cell entry is "disconnected"

**Comment by dvanderb** [comment]
Actually figured out how to do this with the modifier..

**Comment by daringer** [comment]
good to hear that you have sorted it out, I would have suggested modifier anyways being the most flexible solution anyways...

**Comment by thorschtn** [comment]
@dvanderb Would you be so kind as to post an example of how you solved value-dependent formatting with modify? I can't do it. Thanks a lot.
