### ISSUE TITLE
Add support for service call responses

### ISSUE THREAD

**Issue by EdLeckert** [custom-cards/flex-table-card#130]
The core HA team intends to eliminate large entity attribute values by instead encouraging the use of service calls with responses. While this is a somewhat controversial change of direction, as it will cause a good deal of disruption to users, it is in fact happening.

An example of this including their justification is shown in the introduction of the new Weather Service in the [September 2023 Release Notes](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service). 

By its very nature, flex-table-card lends itself very nicely to displaying large amounts of data. Therefore, it is reasonable to assume that some users of the card will be impacted by this shift in strategy as attribute data they depend on is moved gradually to service call responses.

I am submitting a PR as a potential pre-emptive solution to this problem.

As always, comments and suggestions are welcome.

**Comment by daringer** [comment]
merged, releasing this week

**Comment by daringer** [comment]
tested & released in v0.7.6
