### ISSUE TITLE
round decimal places

### ISSUE THREAD

**Issue by nuki47** [custom-cards/flex-table-card#138]
How can I round or cut the decimal places of a sensor value?

<img width="319" alt="image" src="https://github.com/custom-cards/flex-table-card/assets/75117725/2398db7b-605b-4b00-954b-1ca74843a829">

**Comment by EdLeckert** [comment]
As explained in the [docs](docs/example-cfg-simple-cell-formatting.md), you can use:

`    modify: parseFloat(x).toFixed(0)`

in a column definition.

Having said that, I'm working on a feature to allow you to use Home Assistant's standard formatting, which includes the ability to set display precision on entities.
