### ISSUE TITLE
Wrong sorting if mixed plus/minus values

### ISSUE THREAD

**Issue by Klaestrup** [custom-cards/flex-table-card#141]
If the state can be both plus or minus, it sorts the minus values in the wrong order (like it was plus values).

**Comment by EdLeckert** [comment]
It certainly does. I'll take a look.

**Comment by EdLeckert** [comment]
@Klaestrup: Can you confirm that you have non-numeric characters in the states, such as units of measurement? Can you provide a pair of strings that are sorting incorrectly?

**Comment by Klaestrup** [comment]
I'm using counter values:
`entities:
  include: counter.reminder*
sort_by: state+`
And the values are shown like this:
![image](https://github.com/user-attachments/assets/4b04d4b5-ab13-4e3d-9a9d-8ec06b9af093)

**Comment by Klaestrup** [comment]
But 'dage' is not a part of the state, but a suffix (suffix: ' dage'). The I don't expect that it's sorted on this also...?

**Comment by EdLeckert** [comment]
OK, I thought you were using auto_format. You are correct: suffix is not part of the sort.

Do you mind posting your entire card config?

**Comment by Klaestrup** [comment]
Here it is! :-)
`type: custom:flex-table-card
title: Opgaver
sort_by: state+
clickable: true
entities:
  include: counter.reminder*
card_mod:
  style: |
    div {
      padding: 4px;
    }
css:
  table+: 'border-collapse: collapse;'
  th+: 'padding: 8px;'
  td+: 'padding: 16px;'
columns:
  - name: ''
    data: icon
  - name: Opgave
    data: name
    modify: |-
      x = x.replace("Reminder - ", "");
      x;
  - name: Interval
    data: initial
    suffix: ' dage'
  - name: Udføres om
    data: state
    suffix: ' dage'
    modify: |-
      if (parseFloat(x) < 0) {
        x = `<span style="color:red;">${x}</span>`;
      } else if (parseFloat(x) === 0) {
        x = `<span style="color:yellow;">${x}</span>`;
      }
      x;`

**Comment by EdLeckert** [comment]
Just paste it, select all, press the `Code` button:

```
type: custom:flex-table-card
title: Opgaver
sort_by: state+
clickable: true
entities:
  include: counter.reminder*
card_mod:
  style: |
    div {
      padding: 4px;
    }
etc.
```

So your issue is essentially the same as #129. Your HTML or anything added by `modify` becomes part of the sort, and is no longer treated as a numeric but as text. I will see if I can get a PR pushed through to deal with it.
