### ISSUE TITLE
Locale not respected

### ISSUE THREAD

**Issue by Nickduino** [custom-cards/flex-table-card#146]
I live in France. The decimal point is not a point but a comma. Many European countries do this as well. So 1.686 should be 1,686. I haven't checked but I'm sure the delimiter would be "," with your card [when it should be a space (or even a point) in many countries](https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping)

No :
![image](https://github.com/user-attachments/assets/8ab1baa4-cac6-438f-ba64-0d8e9e7a67b7)

Yes:
![image](https://github.com/user-attachments/assets/f875a635-341f-4a0f-9abd-51e868593660)

**Comment by ildar170975** [comment]
Try auto format. 
https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-simple-cell-formatting.md

**Comment by Nickduino** [comment]
> Try auto format.

Thank you!
Surprised it doesn't default to True but I won't complain.


> Suggest you to ask questions in the main dedicated thread in Community.

I'm sorry. I really thought it was an oversight and not a user problem 🥺

**Comment by EdLeckert** [comment]
@Nickduino: The reason `auto_format` is not the default is that it was only added recently, and making it the default would have caused a breaking change and a lot of work for, I would assume, the vast majority of users, since up until that time they had to format their cells manually.

**Comment by Nickduino** [comment]
Thank you for that answer!

**Comment by ildar170975** [comment]
Besides, displaying a “raw” value = less dependency on a volatile HA Frontend.

**Comment by Nickduino** [comment]
> Besides, displaying a “raw” value = less dependency on a volatile HA Frontend.

As a developer, probably. As a user, I'm not sure.
