### ISSUE TITLE
Limiting the number of rows - change the doc

### ISSUE THREAD

**Issue by Nickduino** [custom-cards/flex-table-card#147]
It took me two days to find `max_rows:` in https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-advanced-cell-formatting.md

...because I'm not trying to format _cell content_ but the whole table. 

Would you consider calling it _Advanced Formatting & Modification_?

**Comment by ildar170975** [comment]
Have you considered reading “Configuration reference” chapter?
And ofc many things described in other chapters may be also called “advanced modification” - so renaming the chapter as you proposed will lead to confusion.

**Comment by Nickduino** [comment]
> Have you considered reading “Configuration reference” chapter?

You're right, I missed it
