### ISSUE TITLE
Feature Request: Disable borders

### ISSUE THREAD

**Issue by CWGSM3V0** [custom-cards/flex-table-card#15]
Would be nice if possible. Purely asthetic :)

![image](https://user-images.githubusercontent.com/11978534/66278174-c7065c80-e863-11e9-951a-dbd1bdfbf588.png)

**Comment by daringer** [comment]
There you go, using `css` as config parameter you can now either replace or append provided css via the configuration. For your particular case the following should work:
```
css:
  table+: "border: 0;"
  # note the "+", which is a magic character to signal appending instead of replacing
  # of the provided css-statement
```
in contrast the following would overwrite, i.e., replace the original css:
```
css:
  table: "border:0;"
  # which obviously leads to different results...
```
You can check the current CSS style statements by either using "inspect" within your browser or directly check the source-code starting from here: [line 216](https://github.com/custom-cards/flex-table-card/blob/a5db6ee51c54240b64a304a33b452d87dc43e87f/flex-table-card.js#L216)

Hope this is what you were looking for, also feel free to share an example...

**Comment by daringer** [comment]
also updated the [README.md](https://github.com/custom-cards/flex-table-card/blob/a5db6ee51c54240b64a304a33b452d87dc43e87f/flex-table-card.js) with a more formal usage description.

**Comment by daringer** [comment]
feels completed, closing...
please re-open if needed
