### ISSUE TITLE
Row background color

### ISSUE THREAD

**Issue by micniq** [custom-cards/flex-table-card#26]
Love the card.
Seems like it would make sense to align the row background color choises with what HA uses for their tables: table-row-background-color and table-row-alternative-background-color instead of paper-card-background-color and secondary-background-color. Makes creating themes much easier.

**Comment by daringer** [comment]
still a lot to learn, stupid copy&paste from some years old template, thanks,
could you shortly confirm this works for you?

**Comment by micniq** [comment]
Works great, thanks!
