### ISSUE TITLE
Feature request: click header to sort

### ISSUE THREAD

**Issue by LordShadowen** [custom-cards/flex-table-card#35]
It would be cool if instead of just choosing the sort order once through config, we could click on the header of each column to sort it by that column index.
(the config would still be valid for the default sort)

**Comment by daringer** [comment]
yeah, also had this idea. I have not yet seen this on an element within HA, did you maybe? 

A simple version might be easy to hack-in,but I have some doubts to just re-invent something like that on a *custom-card-level*, means if intended by the lovelace frontend team there would be a nice interface (like the one for bringing up the details window on click).

But a 2nd person is already twice the crowd supporting it (despite me :smile:), so let's see maybe a non-invasive solution might be realistic.

**Comment by myhomeiot** [comment]
> ...so this could act as a blueprint to reverse integrate this into flex-table-card, right?

I think so.

**Comment by EdLeckert** [comment]
Possibly resolved by:

- #107
