### ISSUE TITLE
Renders on every hass update

### ISSUE THREAD

**Issue by htmltiger** [custom-cards/flex-table-card#53]
Hi,

I have added a large table but after adding it the browser was so slow and found the cause to be flex table.
just added this
```
   set hass(hass) {
        const config = this._config;
        const root = this.shadowRoot;
	console.log('set hass');
```
and in the chrome developer tools it is refreshing so many times in a second and it is redrawing the whole table.

I think ```shouldUpdate(changedProps) {... } ``` function should help

Thanks.

**Comment by ildar170975** [comment]
Seems that I see the same issue.
If I open Code Inspector for a flex-table card, I observe a permanent updating of the card:
![a1](https://user-images.githubusercontent.com/71872483/175750573-6415d752-e2aa-4bf4-a245-19f738308516.gif)

**Comment by daringer** [comment]
closed by https://github.com/custom-cards/flex-table-card/pull/103
