### ISSUE TITLE
Abandoned - Alternative?

### ISSUE THREAD

**Issue by hkrob** [custom-cards/flex-table-card#55]
Looks like this card has been abandoned - has anyone found a good alternative?

**Comment by daringer** [comment]
Hey @hkrob, no actually not, but have to admit that can't do much at the moment.
But it's working, right? Or is there something critical that breaks the current functionality?

**Comment by hkrob** [comment]
Thanks, it's working fine and very handy. I was just concerned because on GitHub it says not maintained since 2020 and given the way HA likes to break things .... 

Anyway, thanks for a handy tool
