### ISSUE TITLE
Feature Request: Clickable can be simple toggle

### ISSUE THREAD

**Issue by hathalud** [custom-cards/flex-table-card#58]
I just discovered this custom component today and I'm really impressed with it. I made a card that listed all of my lights and was quite pleased with the options and results. And was a little disappointed that the option "clickable: true" only showed the More Info dialogue box. Would it be possible to make it where More Info OR just a simple toggle is applied as an option instead? Either way, keep up the great work! Thanks so much!

**Comment by daringer** [comment]
Nope, sorry this will not work, especially as the card has an focus on data visualization, thus this not really match with the project's goals. The PopUp info boxes are also not created and populated with contents by the card, this is a ready-to-use-home-assistant element, likely there is a way to modify/change them - but this would mean that you as the user would also have to include this change-set into the card's json data - despite being very painful to use this is a little too far away from a "table visualization card" :smile:
