### ISSUE TITLE
multiple attributes or json object list in one column?

### ISSUE THREAD

**Issue by kl4ppdrachen** [custom-cards/flex-table-card#59]
I want a list for my bus departure, the state and two attributes for the time in one column. In the state is the next bus time with the delay, in the two attributes the two next departure times-

```
 Number | Time  | Direction
  100      | 22:01 | xy
  100      | 22:09 | xy
  100      | 22:15 | xy
```

Is this possible? I only see this for a [json objects](https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-attr-as-list.md).

**Comment by kl4ppdrachen** [comment]
Ok I created my own json object as a sensor. This json object contains both direction:
![grafik](https://user-images.githubusercontent.com/47184285/133158433-2ccc078c-3bea-4c4d-b866-f3c691123d20.png)

Is it possible to list the departure as a list, or multiply "attributes"?
![grafik](https://user-images.githubusercontent.com/47184285/133158576-e677e913-5f7c-4aad-9bb7-ae5eb4cd5428.png)

**Comment by lezioul** [comment]
Hi,

Maybe you solved this, but you can add other columns or concat multiple values in your time column, 
for example 

```
- con: mdi:clock
  attr_as_list: direction
  modify: x.departure.this + ' / ' + modify: x.departure.next+ ' / ' + modify: x.departure.next_on
```

Btw, thanks for this issue, you gave me the opportuniy to solve my own problem to display next train departures 👍
