### ISSUE TITLE
How to display icon as a column value?

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-cards/flex-table-card#60]
![image](https://user-images.githubusercontent.com/35527507/133595051-8ca7b34b-3db2-4083-9092-1fddb676c603.png)

I can’t figure it out. Please help.

Cheers.

**Comment by valleedelisle** [comment]
This worked for me:
```
  - data: icon
    name: Trend
    modify: |
      '<ha-icon icon="' + x + '"/>'
```

**Comment by Tom-ahawk** [comment]
The latest update made this icon code going wrong. Now I see only "/> instead of the icon. Please advise.

**Comment by daringer** [comment]
please try without the modify statement, just use `icon` as data and you should be fine
see: https://github.com/custom-cards/flex-table-card/blob/d352468ff1eea8f467e04b9c65a236575c20968a/flex-table-card.js#L257
