### ISSUE TITLE
Table empty

### ISSUE THREAD

**Issue by WarC0zes** [custom-cards/flex-table-card#69]
Hello,
after the last update, my table is empty and I can't downgrade.
I read the documentation but I don't see what broke my code.

![flex table](https://user-images.githubusercontent.com/91471397/155872497-80ff31a1-6910-4a66-b3e5-9ca9edf8d519.jpg)

```
  - type: custom:flex-table-card
    clickable: false
    entities:
      include: sensor.*_ble
    sort_by: friendly_name
    columns:
      - data: friendly_name
        name: Appareil Bluetooth
        icon: mdi:bluetooth
        modify: x.replace(/Ble/,"")
      - data: mac
        name: MAC
        modify: (x+'').replace(/(.{2}(?!$))/g,"$1:")
        align: center
      - data: msg_received
        name: Received
        modify: 'isNaN(parseInt(x, 10)) ? "" : parseInt(x, 10)'
        align: center
      - data: state
        name: Last Seen
        align: right
        modify: >
          var dt = new Date(0,0,0,0,0,0,(Date.now()-Date.parse(x)));
          isFinite(dt) ? dt.toTimeString().split(" ")[0] : ""
    style: |
      ha-card {
        box-shadow: 0px 2px 4px 0px rgba(0,0,0,1);
      }
```

another card works perfectly
```
  - type: custom:flex-table-card
    max_rows: 5
    sort_by: b7_price+
    clickable: true
    entities:
      include: sensor.carburants*
    columns:
      - data: state
        icon: fas:gas-pump
        align: left
        name: ' CARBURANT'
      - name: Diesel
        data: b7_price
        align: center
      - data: b7_date
        name: Date maj
        align: center
    css:
      tbody tr:nth-child(1): 'color: #00ff00'
      tbody tr:nth-child(5): 'color: #f00020'
    style: |
      :host {
        --card-mod-icon-color: rgb(68, 115, 158);
        font-size: 12.9px;
      }
      ha-card {
        box-shadow: 0px 2px 4px 0px rgba(0,0,0,0);
      }
```
it looks like it doesn't want to consider entity format anymore.

```    entities:
      include: sensor.*_ble
```
Can you help me please.

**Comment by Masterz69** [comment]
```
          - type: 'custom:flex-table-card'
            clickable: true
            entities:
              include:
                - binary_sensor.*_gateway
```
^^ f.e. show empty table.

**Comment by daringer** [comment]
oh noes :/ will look into it ...

**Comment by daringer** [comment]
I just pushed a new state, essentially reverting a cleanup step, which might be evil - but as of now I can't really reproduce it. Could need some more details, like how do the entity ids look like which are not matched...

**Comment by WarC0zes** [comment]
no, as in the photo that I put. Nothing appears in the table. 
 my entity name is: sensor.xxxxxxxxxx_ble

**Comment by BTScroggs** [comment]
I'm getting two errors appear in the logs:
`TypeError: item.slice is not a function
TypeError: content.slice is not a function`

**Comment by daringer** [comment]
> I'm getting two errors appear in the logs: `TypeError: item.slice is not a function TypeError: content.slice is not a function`

that's a good hint, looks like I am being to greedy with catching untested errors :/ please retest, the repository is updated

**Comment by daringer** [comment]
pfew :+1: ok ok, note taken: need a beta branch for testing... thanks for reaching out and reporting!

**Comment by WarC0zes** [comment]
Yes, works perfeclty. Thanks
