### ISSUE TITLE
Consider using releases

### ISSUE THREAD

**Issue by MTrab** [custom-cards/flex-table-card#70]
Perhaps consider using releases - now we get a new version in the UI every time you merge new code.
With releases we only get updates when you create a new release

**Comment by daringer** [comment]
Added a simple release, according to: https://hacs.xyz/docs/publish/start#versions this should work now, but can't seem to find the version number in hacs... guess I we'll see with the next commit

**Comment by daringer** [comment]
Seems not work, the most recent pushes lead to HACS updating again from the repository directly, looks like I am doing something wrong with the release, will check...

**Comment by MTrab** [comment]
You have marked the only release as a pre-release, that's why (pre-release = beta)

**Comment by daringer** [comment]
maaah, you are so right, thanks ;) will make another release und do-it-right(tm)  :D
