### ISSUE TITLE
(line) break when using multiple attribs

### ISSUE THREAD

**Issue by vingerha** [custom-cards/flex-table-card#71]
When using multiple attributes in one column, they are separated by a space. I would like to see each attribute show up on a new line (within the same 'cell')

**Comment by daringer** [comment]
Did you try the `multi_delimiter` property, which exactly has this purpose of replacing the default white-space character between two "multi"-values. The tricky part will be: how to correctly denote the  line-break - I would give `multi_delimiter: "<br />"` a try

**Comment by vingerha** [comment]
That actually did it ...THANKS!
