### ISSUE TITLE
Manually populate the Flex card

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-cards/flex-table-card#73]
I want to make a static list (overview over my IoT items) where I populate the rows and columns manually.
Is this possible with the Flex card? If no, please consider this as an enhancement issue.
Maybe a solution is to use a file (text/Excel) on the HA unit, the user can maintain the file, and the the card displays the data.

**Comment by daringer** [comment]
in general we are talking here about some java-script, which is run by your browser. There is simply not something like per-user-modifiable-data possible within the scope of such a java-script card. BUT you are already using a tool (homeassistant), which keeps data and provides them to the frontend and thus cards. 

So a possible solution for you would be to create an entity within homeassistant and then populate this entity with data (as attribtes), once this is done you can, as with other entities, simply select this entity and display it's data inside your flex-table-card. 

You could even take any arbitrary entity you know it won't vanish, "developer tools" -> "State" -> "Click on the Entity" and there you can easily modify its attributes...
