### ISSUE TITLE
Huge CPU load on server side - probably when using "modify"

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/flex-table-card#81]
I have a test page with ~5..7 cards.
Every card shows a `flex-table-card` with ~5 rows.
Every card represents some example of using `modify` option.
Nothing super complex, just like this:
- math operation like "x * 100";
- string operation like split to substrings;
- convert a timestamp into Datetime.

Every time I open this page I observe a huge CPU load on a server side.
If an average CPU load (measured by `top` command) is 5..20%, now I see it about 95%.
I have to reboot the host then.

![image](https://user-images.githubusercontent.com/71872483/182263686-0a4ec775-057f-4f0f-8f1f-4d1593725da2.png)

Using Chrome, Win10x64 as a client.
Using x86 mini PC as a server (Debian).
HA in Container.

**Comment by daringer** [comment]
this might also be solved by #103

**Comment by ildar170975** [comment]
Seems to be solved!
