### ISSUE TITLE
Unable to use card 

### ISSUE THREAD

**Issue by thyeestes** [custom-cards/flex-table-card#84]
Anyone else has the problem that you cannot use the card? When I try to add it to a dashboard I get this error as soon as file the type.
Cannot read properties of undefined (reading 'map')
type: custom:flex-table-card

Thanks.

**Comment by ildar170975** [comment]
Post a code for the card you are trying to add.

**Comment by thyeestes** [comment]
Ehh I re-installed and it seems to work. Sorry for the inconvenience

**Comment by alanmilinovic** [comment]
I have the same issue. Tried multiple restarts and re-downloading the card in HACS.

Not sure what is wrong and how to fix it. Any idea?

**Comment by alanmilinovic** [comment]
I think this card is broken.

**Comment by alanmilinovic** [comment]
Ok, so it looks like columns definition was missing, lol.
