### ISSUE TITLE
Unable to select (mark) text 

### ISSUE THREAD

**Issue by sepodele** [custom-cards/flex-table-card#91]
When setting up the card, selecting text from the preview works fine and I can copy from the table and paste elsewhere. But when the card is saved I can no longer select text in the table. Is that by design?

**Comment by daringer** [comment]
This is more or less by design, it's simply inherited from parent html-homeassistant-elements I guess... setting `user-select: text` via css should allow you to select text, should be something like this:
```
css:
  'tbody tr+': 'user-select: text'
```
