### ISSUE TITLE
Using variable in css

### ISSUE THREAD

**Issue by cfrets** [custom-cards/flex-table-card#94]
I have a table with energy prices for each hour.

Hour  | Price
00-01 | 0.12
01-02 | 0.34
...

I would like to change the background color on the row containing the price for the current hour.

When hardcoding the hour into the css selector, it works just fine, but when trying to use the current hour, it doesn't work.
How do I make it use a variable?

This work:
`css:
            'tbody tr:nth-child(18}) td': 'background-color: blue'`

This doesn't work:
`css:
            'tbody tr:nth-child({{ new Date().getHours() }}) td': 'background-color: blue'`
or
`css:
            'tbody tr:nth-child({% new Date().getHours() %}) td': 'background-color: blue'`

**Comment by ildar170975** [comment]
Templates are not supported. 
Use card-mod.

**Comment by cfrets** [comment]
I fixed it with card_mod as suggested by @ildar170975 
`card_mod:
    style: |
      tbody tr:nth-child({{ now().hour }}) td {
        background-color: blue;
      }`
