### ISSUE TITLE
Problem with card

### ISSUE THREAD

**Issue by ozzinse** [custom-cards/flex-table-card#96]
Once installed, the card cannot be selected on the dashboard (clear cahe / restart 3, 4 times) 
I have this error: 
```
Cannot read properties of undefined (reading 'map')
type: custom:flex-table-card
```

**Comment by dominatorstang** [comment]
updated to the latest version on HA and HASS and even tried beta version of flex-table-card 0.7.1.  All have the same results.

**Comment by fredoune77** [comment]
Same issue for me !
Home Assistant 2023.4.4
Flex table : v.0.7.2

**Comment by ildar170975** [comment]
> the card cannot be selected on the dashboard

What do you mean by "selected"?
The card does not have UI settings.
You need to use yaml.
