### ISSUE TITLE
Cannot sort by battery level

### ISSUE THREAD

**Issue by rasskjo** [custom-cards/flex-table-card#99]
Why won't my list sort by battery level?

![image](https://github.com/custom-cards/flex-table-card/assets/119779083/50c5dcf2-d66f-4e04-9010-b114d5700f4d)

**Comment by ildar170975** [comment]
Probably because you are using a wrong name for the `sort_by` option.

**Comment by rasskjo** [comment]
God damn, it worked. Thanks alot. I would be really great if there was some build-in syntax help in HA
